<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class SubscriptionController extends Controller
{
    //
    
    function create(){
        
        $subscription = 200; //$_POST['amount'];
        $data = array(
        "amount" => number_format($subscription, 2),//format amount to 2 decimal places

        "desc" => "Masomo trivia subscription",
        "type" => 'MERCHANT',
        "reference" => 3434,//unique order id of the transaction, generated by merchant
        "first_name" => \Auth::user()->name,
        "last_name" => \Auth::user()->name,
        "email" => \Auth::user()->email,
        "phonenumber" => \Auth::user()->mobile,
        );
        return view("subscription.create", compact('data'));
    }
    
    function storages(){
        $trackid = Input::get('pesapal_transaction_tracking_id');
        $reference = Input::get('pesapal_merchant_reference');
        $subscription = new App\Subscription();
        $today = new Carbon();
        $subscription->track_id = $trackid;
        $subscription->reference_id = $reference;
        $subscription->user_id = \Auth::user()->id;
        $subscription->amount = 200;
        $subscription->expiry_date = $today->addDays(30);
        $subscription->save();
        \Session::flash('success',"The payment has been received, waiting for approval, the expiry date will be on $subscription->expiry_date");
        return redirect('users/profile');
    }
}
